name: geo_track_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - "app/"
  - "packages/**"

scripts:
  analyze:
    exec: sh "$MELOS_ROOT_PATH/.scripts/linter.sh"

  build:
    exec: sh "$MELOS_ROOT_PATH/.scripts/build.sh"

  get:
    exec: fvm flutter pub get

  clean:
    exec: fvm flutter clean

  purge:
    exec: sh "$MELOS_ROOT_PATH/.scripts/purge.sh"