name: geo_track_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - "app/"
  - "packages/**"

scripts:
  linter:
    exec: sh "$MELOS_ROOT_PATH/.scripts/linter.sh"

  build:
    exec: sh "$MELOS_ROOT_PATH/.scripts/build.sh"

  pub_get:
    exec: sh "$MELOS_ROOT_PATH/.scripts/pub_get.sh"

  clean:
    exec: sh "$MELOS_ROOT_PATH/.scripts/clean.sh"

  purge:
    exec: sh "$MELOS_ROOT_PATH/.scripts/purge.sh"

  sync_setup:
    # packageFilters:
    #   ignore: 
    #     - "geo_track_pro"
    exec: bash "$MELOS_ROOT_PATH/.scripts/sync_setup.sh"
  
  coverage:
    exec: sh "$MELOS_ROOT_PATH/.scripts/coverage.sh"