name: geo_track_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - "app/*"
  - "packages/**"

scripts:
  analyze:
    exec: dart analyze

  build:
    exec: fvm dart run build_runner build --delete-conflicting-outputs && fvm flutter gen-l10n

  get:
    exec: fvm flutter pub get

  clean:
    exec: fvm flutter clean
