name: geo_track_pro
description: "A new Flutter project."

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  auth_package:
    path: ../packages/auth_package
  commons_package:
    path: ../packages/commons_package
  cupertino_icons: ^1.0.8
  envied: ^1.3.5
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_localization: ^0.4.0
  flutter_riverpod: ^3.3.1
  go_router: ^17.3.0
  home_package:
    path: ../packages/home_package
  riverpod: ^3.2.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
